## указать адрес имя и пароль в базу данных
## базу поднять с помощью докер
spring.datasource.url=jdbc:postgresql://localhost:5436/customer_control_db
spring.datasource.username=postgres
spring.datasource.password=postgres123